### ISSUE TITLE
机翻机器人能支持登陆吗

### ISSUE THREAD

**Issue by ts8zs** [jiwangyihao/source-j-legado#1]
需要在header Authorization里面带上localstorage.authInfo的token

**Comment by jiwangyihao** [comment]
这个登录有什么特别功能吗，我等下试一下

**Comment by ts8zs** [comment]
搜索结果不一样 然后收藏的接口和搜索是一样的可以做发现

**Comment by jiwangyihao** [comment]
能举个例子吗（
方便测试

**Comment by ts8zs** [comment]
登录前
![image](https://github.com/jiwangyihao/source-j-legado/assets/6174819/250be462-120a-4836-874b-8350e4e833f5)
登录后(账号注册一个月以上)
![image](https://github.com/jiwangyihao/source-j-legado/assets/6174819/0ff59f4f-3b83-481a-a7e1-c9d1c66e7df4)

**Comment by ts8zs** [comment]
`{{
var a= JSON.parse(java.webView("", "https://books.fishhawk.top/",'localStorage.getItem("authInfo")'));
java.log(JSON.stringify(a))
if(a.info.token){
var token=a.info.token;
}
java.log(token);
}}`
试了一下拿到token了但是不知道header怎么用不了

**Comment by jiwangyihao** [comment]
我倾向于直接模拟登录请求来着（
阅读的机制是在执行登录请求的时候保存登录头（
这几天挺忙的😂在准备微积分考试，大概过一段时间会处理的

**Comment by jiwangyihao** [comment]
大体上完成了
https://shuyuan.mgz6.cc/shuyuan/12dac23584f8a439b417ba5542e4dea4.json

**Comment by jiwangyihao** [comment]
https://github.com/jiwangyihao/source-j-legado/commit/83117458431ae491a97c012be19df5cda05431de

https://www.coolapk.com/feed/54983229?shareKey=ZTgzZjQ4YjJlM2UyNjYzOWM3ZDE~&shareUid=1399429&shareFrom=com.coolapk.market_14.1.2

已正式发布
