### ISSUE TITLE
异常的字

### ISSUE THREAD

**Issue by XHXYT** [jiwangyihao/source-j-legado#2]
在轻小说《无名记忆》的正文里，有的时候会发生一些奇怪的混乱（此处为第一卷第六章的第四页最后部分），
![Screenshot_20240424_232415_io legado app releaseA](https://github.com/jiwangyihao/source-j-legado/assets/106398898/07f464d2-4a69-42b4-a933-e677582346a1)
对比哔哩轻小说网站里的界面发现是在部分段落即将与下一页拼接的最后一点文本的字与其它不一样，好像字体变得更小了
![Screenshot_20240424_232348_com huawei browser](https://github.com/jiwangyihao/source-j-legado/assets/106398898/6c7f688c-29a9-4a8e-a702-418183f52ad3)
阅读版本号为：3.24.031000

**Comment by jiwangyihao** [comment]
问题已知，经确认是字体替换。
目前的话需要等阅读那边完善API（见 https://github.com/gedoor/legado/issues/3893 的讨论）
以及哔轻目前包含此机制的内容较少（只有少量章节的最后一段），推断站长也还未完全完成此功能

目前计划在周末的时候处理
另外非要在阅读里查看乱码文字的话可尝试直接将字体更换为[防盗版小米兰亭](https://www.bilinovel.com/public/font/read.ttf)（这会导致正常段落乱码）

**Comment by XHXYT** [comment]
我还发现一个很神奇的现象，同样的一个地方我在手机上看会乱码，但是换成平板（阅读版本与手机相同）看就不会，非常神奇
![Screenshot_20240425_081521_io legado app releaseA_edit_137647362727953](https://github.com/jiwangyihao/source-j-legado/assets/106398898/9365e7b3-50f2-4b17-81e8-b02c3a84b803)

**Comment by jiwangyihao** [comment]
推断是缓存没有刷新/站长故意的做成随机触发（

**Comment by jiwangyihao** [comment]
阅读已经处理了之前的 API 问题

> fix with commit cb06d14
> Test Build [#4618](https://github.com/gedoor/legado/actions/runs/8857424485)

我会在近两天处理这个问题

**Comment by jiwangyihao** [comment]
试一下吧https://shuyuan.mgz6.cc/shuyuan/697b8da75270b9dca775114ac6796bb2.json

**Comment by XHXYT** [comment]
已经OK了，感谢大佬
