### ISSUE TITLE
获取正文出错

### ISSUE THREAD

**Issue by wulei1997** [jiwangyihao/source-j-legado#3]
![Screenshot_2024-06-08-09-39-26-644_io legado app release](https://github.com/jiwangyihao/source-j-legado/assets/53397694/f392279f-af6b-46ed-82ee-d84de765c742)

**Comment by jiwangyihao** [comment]
试一下https://shuyuan.miaogongzi.cc/shuyuan/b0036c10e5c3a1d31ef76240b8cc8899.json

**Comment by 2971567549** [comment]
> 试一下https://shuyuan.miaogongzi.cc/shuyuan/b0036c10e5c3a1d31ef76240b8cc8899.json

过期了

**Comment by jiwangyihao** [comment]
> > 试一下https://shuyuan.miaogongzi.cc/shuyuan/b0036c10e5c3a1d31ef76240b8cc8899.json
> 
> 大佬过期了😭

GitHub已更新，从readme中的链接重新导入即可
