### ISSUE TITLE
真白萌除了正文，其他都用不了

### ISSUE THREAD

**Issue by wulei1997** [jiwangyihao/source-j-legado#4]
![Screenshot_2024-06-18-10-27-20-180_io legado app release](https://github.com/jiwangyihao/source-j-legado/assets/53397694/e02caf31-8d48-42d1-8e65-297d762c55e2)

**Comment by jiwangyihao** [comment]
https://github.com/jiwangyihao/source-j-legado/commit/c12b28b17dbf63da9af486404aae8c6fcb9676df

已处理
