### ISSUE TITLE
爱阅书香 & 源阅

### ISSUE THREAD

**Issue by alphavvv** [jiwangyihao/source-j-legado#5]
请问考虑写爱阅书香的书源吗，比较缺轻小说的源
另外源阅读也是部分支持阅读3.0的书源的，但是尝试导入了一下，除了三七的源以外其他貌似还需要适配一下才行

非常感谢大佬的付出

**Comment by jiwangyihao** [comment]
爱阅书香暂时不太考虑，因为没有苹果设备测试

源阅读里部分源用不了是因为不支持我使用的特性，暂时不考虑适配

**Comment by jiwangyihao** [comment]
大部分源阅读里用不了的源应该主要是发现用不了，这个可以尝试自己参照其他源写一下发现规则，应该只要填分类名称加网址就行

部分其他功能也不能使用的源里用到的特性是必要的（比如哔哩轻小说的字体替换），这个无法适配
