### ISSUE TITLE
机翻机器人能支持添加网址吗

### ISSUE THREAD

**Issue by SaiCateDoan** [jiwangyihao/source-j-legado#6]
现在尝试直接添加网址的时候必定会失败
跟 #1 相关的需求，部分小说新用户无法搜索到，但是如果别人分享链接仍然可以直接看

PS：现在可以通过网页收藏->登录书源->发现->默认收藏夹的方式曲线救国

PPS：我就不该图轻松没注册账号

**Comment by SaiCateDoan** [comment]
顺便，不知道能否兼容不带/api的地址

**Comment by jiwangyihao** [comment]
简单处理了一下，试试吧

https://shuyuan.miaogongzi.cc/shuyuan/b13fcac62462b714c9a170f4d0d072b5.json

**Comment by SaiCateDoan** [comment]
可以了，非常感谢
不带/api的情况下会无法获取目录，不过无所谓了，本来想看看能否自动补上/api，看了一眼开源阅读好像不支持自动修改网址
顺便提供两个无法搜索的样例：https://books.fishhawk.top/api/novel/syosetu/n7820gz
https://books.fishhawk.top/api/novel/kakuyomu/16816927863204515918

**Comment by jiwangyihao** [comment]
其实写了补api的处理的（
现在应该可以添加无api的链接了
https://shuyuan.miaogongzi.cc/shuyuan/08c354f5567300de973ec366f6defe7c.json

**Comment by SaiCateDoan** [comment]
好像没有问题了
