### ISSUE TITLE
机翻机器人能支持book1版本吗

### ISSUE THREAD

**Issue by SaiCateDoan** [jiwangyihao/source-j-legado#7]
https://books1.fishhawk.top/
需要翻墙的主站，可以在book没法访问的时候使用
我已经自己修改了一份，但是放进书源里可以方便后续更新，非常感谢

**Comment by jiwangyihao** [comment]
能问一下「修改」指具体进行了哪些操作吗
（在写源的时候其实有考虑换域名问题，因此大多数地方都尽量做了处理）

以只修改「源url」字段即可完成迁移为目标的话，你觉得下面这个版本是否符合？
https://shuyuan.miaogongzi.cc/shuyuan/247162f0da7973724f22b87216ef2f16.json

还有一个问题是，已经添加的小说的检索url不会受到源url改变的影响，这个问题实际用的时候也比较麻烦，像哔轻一样拆成两个源倒也不是不行，但如果只有一个字段的区别的话好像感觉不够必要？（另外也许会影响设置的书籍变量之类的？）

**Comment by SaiCateDoan** [comment]
非常粗暴的复制了一份书源，然后把所有找到的book替换成book1，包括但不限于源url，书籍正则url，搜索url，因为替换的很粗暴，所以不确定有没有问题，我只是发现小说能看就没管了
另外我个人建议还是跟哔哩轻小说一样分两个源，但是如果要只支持book1我也没意见

**Comment by jiwangyihao** [comment]
那么我新发的这个版本在只更改源url的情况下是否可以正常工作？（

**Comment by SaiCateDoan** [comment]
在有两个书源的情况下，能搜索到的小说换源还是很轻松的，搜索不到的小说需要手动换

**Comment by jiwangyihao** [comment]
机器人这个源会用到书籍变量来自定义正文展示方式，换源可能会影响到这部分我觉得（

**Comment by SaiCateDoan** [comment]
我没理解上面发的书源的含义，是让我手动在源url后面补个1吗

**Comment by jiwangyihao** [comment]
是

**Comment by SaiCateDoan** [comment]
刚刚出现了在存在书籍的情况下修改书源，然后始终无法换源成功，但是我把书籍删掉后重新导入操作了半天没法复现，现在工作一切正常
这里是无法搜索的书籍样例：https://books.fishhawk.top/api/novel/syosetu/n7820gz

**Comment by SaiCateDoan** [comment]
大致搞懂了，具体流程如下：
使用book书源->输入book1网址->切换到book1书源
然后这本书就只能删了再导入（前提是无法搜索）

**Comment by SaiCateDoan** [comment]
我觉得直接使用book1书源可解（）

**Comment by jiwangyihao** [comment]
虽然在我这里book1似乎不需要翻墙，但在我这里我也从未见过book主站不可用的情况（
默认提供一个可能需要翻墙的地址看起来并不优雅（

另外，就目前阅读的机制来说，某本小说的索引url总是保持添加时的状态不变，这个问题似乎没办法解决（也就是更改域名后总是需要删除再添加这一点）

如果book1在你所在地区更好用，我觉得提供一个足够快捷的修改方式就足够了（大概）

**Comment by SaiCateDoan** [comment]
我也觉得，这样就可以了，主要是今天book站好像崩了几个小时

**Comment by SaiCateDoan** [comment]
总之非常感谢

**Comment by SaiCateDoan** [comment]
> 大致搞懂了，具体流程如下： 使用book书源->输入book1网址->切换到book1书源 然后这本书就只能删了再导入（前提是无法搜索）

关于这个问题，我意识到了一个很幽默的解决方案：用如果用book1网址不行，那就用book网址，这样就能不删书重新识别（虽然里面内容还是会被清空（好像跟删书还是没啥区别））

不过正常情况下应该是导入书源后选定book或者book1站，然后永远不改变，所以上面那个仅供参考，不具备实际意义
