### ISSUE TITLE
哔哩哔哩轻小说书源正文获取失败

### ISSUE THREAD

**Issue by wulei1997** [jiwangyihao/source-j-legado#8]
![Uploading Screenshot_2024-09-16-11-09-16-869_io.legado.app..jpg…]()

**Comment by wulei1997** [comment]
![Screenshot_2024-09-16-11-09-16-869_io legado app](https://github.com/user-attachments/assets/4cd20a9d-3993-4b02-be7d-fd8f45ca9540)

**Comment by jiwangyihao** [comment]
试一下吧：https://shuyuan.miaogongzi.cc/shuyuan/0470f9598626c890d115adaec1951f97.json

**Comment by swttkonjjj** [comment]
![Screenshot_2024-11-18-00-53-51-139_io legado app release](https://github.com/user-attachments/assets/6b596699-4acf-4b83-80af-478a9cb8582e)
https://www.bilinovel.com/search.html?searchkey=我的初恋太过羞耻无法对人诉说&searchtype=all
在正文章节加载不出来，一直显示加载数据中
